## 1. Visualising the data and removing Null values

In [1]:
import pandas as pd 
import numpy as np
import re

In [2]:
df = pd.read_csv('personality_scores.csv', sep=";")
df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 70 columns):
ID                                                                          1555 non-null int64
Section 5 of 6 [I am always prepared.]                                      1555 non-null object
Section 5 of 6 [I am easily disturbed.]                                     1555 non-null object
Section 5 of 6 [I am exacting (demanding) in my work.]                      1555 non-null object
Section 5 of 6 [I am full of ideas.]                                        1555 non-null object
Section 5 of 6 [I am interested in people.]                                 1555 non-null object
Section 5 of 6 [I am not interested in abstract ideas.]                     1555 non-null object
Section 5 of 6 [I am not interested in other people's problems.]            1555 non-null object
Section 5 of 6 [I am not really interested in others.]                      1555 non-null object
Section 5 of 6 [I am quick to understand things.]                           1555 non-null object
Section 5 of 6 [I am quiet around strangers.]                               1555 non-null object
Section 5 of 6 [I am relaxed most of the time.]                             1555 non-null object
Section 5 of 6 [I am the life of the party.]                                1555 non-null object
Section 5 of 6 [I change my mood a lot.]                                    1555 non-null object
Section 5 of 6 [I do not have a good imagination.]                          1555 non-null object
Section 5 of 6 [I don't like to draw attention to myself.]                  1555 non-null object
Section 5 of 6 [I don't mind being the center of attention.]                1555 non-null object
Section 5 of 6 [I don't talk a lot.]                                        1555 non-null object
Section 5 of 6 [I feel comfortable around people.]                          1555 non-null object
Section 5 of 6 [I feel little concern for others.]                          1555 non-null object
Section 5 of 6 [I feel others' emotions.]                                   1555 non-null object
Section 5 of 6 [I follow a schedule.]                                       1555 non-null object
Section 5 of 6 [I get chores done right away.]                              1555 non-null object
Section 5 of 6 [I get irritated easily.]                                    1555 non-null object
Section 5 of 6 [I get stressed out easily.]                                 1555 non-null object
Section 5 of 6 [I get upset easily.]                                        1555 non-null object
Section 5 of 6 [I have a rich vocabulary.]                                  1555 non-null object
Section 5 of 6 [I have a soft (kind) heart.]                                1555 non-null object
Section 5 of 6 [I have a vivid imagination.]                                1555 non-null object
Section 5 of 6 [I have difficulty understanding abstract ideas.]            1555 non-null object
Section 5 of 6 [I have excellent ideas.]                                    1555 non-null object
Section 5 of 6 [I have frequent mood swings.]                               1555 non-null object
Section 5 of 6 [I have little to say.]                                      1555 non-null object
Section 5 of 6 [I insult people.]                                           1555 non-null object
Section 5 of 6 [I keep in the background.]                                  1555 non-null object
Section 5 of 6 [I leave my belongings lying around.]                        1555 non-null object
Section 5 of 6 [I like order.]                                              1555 non-null object
Section 5 of 6 [I make a mess of things.]                                   1555 non-null object
Section 5 of 6 [I make people feel at ease.]                                1555 non-null object
Section 5 of 6 [I neglect my duties.]                                       1555 non-null object
Section 5 of 6 [I often feel blue (down).]                                  1555 non-null object
Section 5 of 6 [I often forget to put things back in their proper place]    1555 non-null object
Section 5 of 6 [I pay attention to details.]                                1555 non-null object
Section 5 of 6 [I seldom feel blue (down).]                                 1555 non-null object
Section 5 of 6 [I spend time reflecting on things.]                         1555 non-null object
Section 5 of 6 [I start conversations.]                                     1555 non-null object
Section 5 of 6 [I sympathize with others' feelings.]                        1555 non-null object
Section 5 of 6 [I take time out for others.]                                1555 non-null object
Section 5 of 6 [I talk to a lot of different people at parties.]            1555 non-null object
Section 5 of 6 [I use difficult words.]                                     1555 non-null object
Section 5 of 6 [I worry about things.]                                      1555 non-null object
Unnamed: 51                                                                 0 non-null float64
Unnamed: 52                                                                 0 non-null float64
Unnamed: 53                                                                 0 non-null float64
Unnamed: 54                                                                 0 non-null float64
Unnamed: 55                                                                 0 non-null float64
Unnamed: 56                                                                 0 non-null float64
Unnamed: 57                                                                 0 non-null float64
Unnamed: 58                                                                 0 non-null float64
Unnamed: 59                                                                 0 non-null float64
Unnamed: 60                                                                 0 non-null float64
Unnamed: 61                                                                 0 non-null float64
Unnamed: 62                                                                 0 non-null float64
Unnamed: 63                                                                 0 non-null float64
Unnamed: 64                                                                 0 non-null float64
Unnamed: 65                                                                 0 non-null float64
Unnamed: 66                                                                 0 non-null float64
Unnamed: 67                                                                 0 non-null float64
Unnamed: 68                                                                 0 non-null float64
IPIP_HIGH_RISK                                                              0 non-null float64
dtypes: float64(19), int64(1), object(50)
memory usage: 850.5+ KB

In [4]:
new_df = df.drop_duplicates(keep="first")
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1555 entries, 0 to 1554
Data columns (total 70 columns):
ID                                                                          1555 non-null int64
Section 5 of 6 [I am always prepared.]                                      1555 non-null object
Section 5 of 6 [I am easily disturbed.]                                     1555 non-null object
Section 5 of 6 [I am exacting (demanding) in my work.]                      1555 non-null object
Section 5 of 6 [I am full of ideas.]                                        1555 non-null object
Section 5 of 6 [I am interested in people.]                                 1555 non-null object
Section 5 of 6 [I am not interested in abstract ideas.]                     1555 non-null object
Section 5 of 6 [I am not interested in other people's problems.]            1555 non-null object
Section 5 of 6 [I am not really interested in others.]                      1555 non-null object
Section 5 of 6 [I am quick to understand things.]                           1555 non-null object
Section 5 of 6 [I am quiet around strangers.]                               1555 non-null object
Section 5 of 6 [I am relaxed most of the time.]                             1555 non-null object
Section 5 of 6 [I am the life of the party.]                                1555 non-null object
Section 5 of 6 [I change my mood a lot.]                                    1555 non-null object
Section 5 of 6 [I do not have a good imagination.]                          1555 non-null object
Section 5 of 6 [I don't like to draw attention to myself.]                  1555 non-null object
Section 5 of 6 [I don't mind being the center of attention.]                1555 non-null object
Section 5 of 6 [I don't talk a lot.]                                        1555 non-null object
Section 5 of 6 [I feel comfortable around people.]                          1555 non-null object
Section 5 of 6 [I feel little concern for others.]                          1555 non-null object
Section 5 of 6 [I feel others' emotions.]                                   1555 non-null object
Section 5 of 6 [I follow a schedule.]                                       1555 non-null object
Section 5 of 6 [I get chores done right away.]                              1555 non-null object
Section 5 of 6 [I get irritated easily.]                                    1555 non-null object
Section 5 of 6 [I get stressed out easily.]                                 1555 non-null object
Section 5 of 6 [I get upset easily.]                                        1555 non-null object
Section 5 of 6 [I have a rich vocabulary.]                                  1555 non-null object
Section 5 of 6 [I have a soft (kind) heart.]                                1555 non-null object
Section 5 of 6 [I have a vivid imagination.]                                1555 non-null object
Section 5 of 6 [I have difficulty understanding abstract ideas.]            1555 non-null object
Section 5 of 6 [I have excellent ideas.]                                    1555 non-null object
Section 5 of 6 [I have frequent mood swings.]                               1555 non-null object
Section 5 of 6 [I have little to say.]                                      1555 non-null object
Section 5 of 6 [I insult people.]                                           1555 non-null object
Section 5 of 6 [I keep in the background.]                                  1555 non-null object
Section 5 of 6 [I leave my belongings lying around.]                        1555 non-null object
Section 5 of 6 [I like order.]                                              1555 non-null object
Section 5 of 6 [I make a mess of things.]                                   1555 non-null object
Section 5 of 6 [I make people feel at ease.]                                1555 non-null object
Section 5 of 6 [I neglect my duties.]                                       1555 non-null object
Section 5 of 6 [I often feel blue (down).]                                  1555 non-null object
Section 5 of 6 [I often forget to put things back in their proper place]    1555 non-null object
Section 5 of 6 [I pay attention to details.]                                1555 non-null object
Section 5 of 6 [I seldom feel blue (down).]                                 1555 non-null object
Section 5 of 6 [I spend time reflecting on things.]                         1555 non-null object
Section 5 of 6 [I start conversations.]                                     1555 non-null object
Section 5 of 6 [I sympathize with others' feelings.]                        1555 non-null object
Section 5 of 6 [I take time out for others.]                                1555 non-null object
Section 5 of 6 [I talk to a lot of different people at parties.]            1555 non-null object
Section 5 of 6 [I use difficult words.]                                     1555 non-null object
Section 5 of 6 [I worry about things.]                                      1555 non-null object
Unnamed: 51                                                                 0 non-null float64
Unnamed: 52                                                                 0 non-null float64
Unnamed: 53                                                                 0 non-null float64
Unnamed: 54                                                                 0 non-null float64
Unnamed: 55                                                                 0 non-null float64
Unnamed: 56                                                                 0 non-null float64
Unnamed: 57                                                                 0 non-null float64
Unnamed: 58                                                                 0 non-null float64
Unnamed: 59                                                                 0 non-null float64
Unnamed: 60                                                                 0 non-null float64
Unnamed: 61                                                                 0 non-null float64
Unnamed: 62                                                                 0 non-null float64
Unnamed: 63                                                                 0 non-null float64
Unnamed: 64                                                                 0 non-null float64
Unnamed: 65                                                                 0 non-null float64
Unnamed: 66                                                                 0 non-null float64
Unnamed: 67                                                                 0 non-null float64
Unnamed: 68                                                                 0 non-null float64
IPIP_HIGH_RISK                                                              0 non-null float64
dtypes: float64(19), int64(1), object(50)
memory usage: 862.5+ KB

In [5]:
df.dropna(axis=1, how="all", inplace = True)

In [6]:
df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

In [7]:
assert len(df) == len(new_df)

### 2. Create new columns containing the total score of each of the personality test subscales.

In [8]:
# funtion for creating the scores of the new columns 
def convertData(row, Nums_Cat):
    count = 0
    for values in df.columns:
        lst = row[values]
        if type(lst) == str:
            cat = lst[1]
            result = int(lst[4])
            if cat == Nums_Cat:
                count += result
    return count

In [9]:
# applying the function above to the new columns 
df['Extraversion'] = df.apply(lambda row : convertData(row,'1'), axis = 1)
df['Agreeableness'] = df.apply(lambda row : convertData(row,'2'), axis = 1)
df['Conscientiousness'] = df.apply(lambda row : convertData(row,'3'), axis = 1)
df['Emotional Stability'] = df.apply(lambda row : convertData(row,'4'), axis = 1)
df['openness'] = df.apply(lambda row : convertData(row,'5'), axis = 1)

In [10]:
# printing the new dataset with new columns
df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability,openness
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36

# Question 2

 1. Importing the data, merging data and using the asssert statement to see if the lengths of the DataFrame is equal(==)

In [11]:
# Using Pandas to read into the file
df_departments = pd.read_csv('departments.csv', sep=';')
df_departments.head()

   ID Department
0   0       Data
1   1       Data
2   2       Data
3   3       Data
4   4       Data

In [12]:
# Merging the two DataFrame using Pandas(pd)
df_merge = pd.merge(df, df_departments, on=None, how='outer')
df_merge.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability,openness,Department
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42,Data
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42,Data
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42,Data
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38,Data
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36,Data

In [13]:
# using the assert statement to see if the length(len) of DataFrame is equal
assert len(df_departments) == len(df_merge)

*Trying to see if the length of the merged and department DataFrame is equal.

*We have CONCLUDED that they are equal length

#### 2. Creating a condition that has to be met by the columns (named) and a new DataFrames

In [14]:
# finding the values that are less than 30 in the three columns 
df_merge[(df_merge['Agreeableness'] < 30) & (df_merge['Emotional Stability'] < 30) & (df_merge['Conscientiousness'] < 30)]

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability,openness,Department
881,881,"(3, 3)","(4, 1)","(3, 1)","(5, 5)","(2, 1)","(5, 3)","(2, 5)","(2, 3)","(5, 3)",...,"(2, 3)","(1, 5)","(5, 1)","(4, 1)",30,28,26,28,36,Data
1197,1197,"(3, 5)","(4, 5)","(3, 1)","(5, 1)","(2, 1)","(5, 3)","(2, 5)","(2, 1)","(5, 1)",...,"(2, 1)","(1, 3)","(5, 5)","(4, 1)",40,22,26,26,28,Copywriting

In [15]:
# creating a new DataFrame with the columns stated below
Risk_status = pd.DataFrame(df_merge[['ID','Extraversion','Agreeableness','Conscientiousness','Emotional Stability','openness','Department']])
Risk_status.head()

,ID,Extraversion,Agreeableness,Conscientiousness,Emotional Stability,openness,Department
0,0,30,40,48,36,42,Data
1,1,42,46,46,40,42,Data
2,2,28,40,40,38,42,Data
3,3,30,38,38,40,38,Data
4,4,28,34,46,38,36,Data

In [16]:
# funtion that is creating the high and low of the new columns
def risk_status(score, name):
    mean = df_merge[name].mean()
    standiv = df_merge[name].std()
    high = (mean + standiv)/2
    low = (mean - standiv)/2
    if score >= high:
        return 'high'
    else:
        return 'low'

In [17]:
# creating new columns for the merged DataFrame and calling the relevant columns  
df_merge['Extraversion levels'] = df_merge['Extraversion'].apply(lambda column : risk_status(column,'Extraversion'))
df_merge['Agreeableness levels'] = df_merge['Agreeableness'].apply(lambda column : risk_status(column,'Agreeableness'))
df_merge['Conscientiousness levels'] = df_merge['Conscientiousness'].apply(lambda column : risk_status(column,'Conscientiousness'))
df_merge['Emotional Stability levels'] = df_merge['Emotional Stability'].apply(lambda column : risk_status(column,'Emotional Stability'))
df_merge['openness levels'] = df_merge['openness'].apply(lambda column : risk_status(column,'openness'))
df_merge.loc[:, 'Agreeableness':'openness levels']

,Agreeableness,Conscientiousness,Emotional Stability,openness,Department,Extraversion levels,Agreeableness levels,Conscientiousness levels,Emotional Stability levels,openness levels
0,40,48,36,42,Data,high,high,high,high,high
1,46,46,40,42,Data,high,high,high,high,high
2,40,40,38,42,Data,high,high,high,high,high
3,38,38,40,38,Data,high,high,high,high,high
4,34,46,38,36,Data,high,high,high,high,high
...,...,...,...,...,...,...,...,...,...,...
1550,48,38,44,44,Web dev,high,high,high,high,high
1551,48,40,44,34,Web dev,high,high,high,high,high
1552,44,40,46,48,Web dev,high,high,high,high,high
1553,38,48,36,44,Web dev,high,high,high,high,high
1554,44,42,40,30,Web dev,high,high,high,high,high

In [18]:
# we are creating a new column called  
Risk_status['Risk Status'] = np.where(
    (Risk_status['Emotional Stability'] < 30) & \
    (Risk_status.Conscientiousness < 30) & (Risk_status.Agreeableness < 30), 'High risk', 'Low risk')
Risk_status.head()

,ID,Extraversion,Agreeableness,Conscientiousness,Emotional Stability,openness,Department,Risk Status
0,0,30,40,48,36,42,Data,Low risk
1,1,42,46,46,40,42,Data,Low risk
2,2,28,40,40,38,42,Data,Low risk
3,3,30,38,38,40,38,Data,Low risk
4,4,28,34,46,38,36,Data,Low risk

In [42]:
# we are calling the columns, grouping them and making them into a DataFrame 
summary = Risk_status[['Risk Status', 'Department']].groupby(['Risk Status', 'Department']).size()
pd.DataFrame(summary)

                           0
Risk Status Department
High risk   Copywriting    1
            Data           1
Low risk    Copywriting  325
            Data         328
            Design       120
            Strategy     449
            Web Dev      170
            Web dev      161

In [48]:
summary = pd.pivot_table(summary, index=['Risk Status'],  columns=['Department'], margins=True, aggfunc=np.sum)

AttributeError: 'Series' object has no attribute 'columns'

In [40]:
summary

            Agreeableness                                                   \
Department    Copywriting     Data  Design Strategy Web Dev Web dev    All
Risk Status
High risk            22.0     28.0     NaN      NaN     NaN     NaN     50
Low risk          13630.0  13924.0  5020.0  18970.0  7148.0  6848.0  65540
All               13652.0  13952.0  5020.0  18970.0  7148.0  6848.0  65590

            Conscientiousness                   ...       ID            \
Department        Copywriting     Data  Design  ...  Web Dev   Web dev
Risk Status                                     ...
High risk                26.0     26.0     NaN  ...      NaN       NaN
Low risk              13724.0  13958.0  5024.0  ...  19295.0  237314.0
All                   13750.0  13984.0  5024.0  ...  19295.0  237314.0

                        openness                                            \
Department       All Copywriting     Data  Design Strategy Web Dev Web dev
Risk Status
High risk       2078        28.0     36.0     NaN      NaN     NaN     NaN
Low risk     1206157     12776.0  13418.0  4794.0  18172.0  6862.0  6248.0
All          1208235     12804.0  13454.0  4794.0  18172.0  6862.0  6248.0


Department     All
Risk Status
High risk       64
Low risk     62270
All          62334

[3 rows x 42 columns]